apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spin
  namespace: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 1.32.0
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: spinnaker
          rootFolder: front50
          accessKeyId: admin
          secretAccessKey: admin12345
          region: us-east-1
          endpoint: http://minio.minio:9000
          pathStyleAccess: true
      security:
        authn:
          enabled: false
        authz:
          enabled: false
    profiles:
      deck:
        settings-local.js: |
          window.spinnakerSettings = window.spinnakerSettings || {};
          // Make Deck call Gate on your local port-forward
          window.spinnakerSettings.gateUrl = 'http://localhost:8084';
      gate:
        cors:
          enabled: true
          # Allow Deck on localhost:9000 to call Gate on localhost:8084
          allowedOriginsPattern: '^http://localhost:9000$'
  expose:
    type: service
    service:
      type: ClusterIP
